=== Emotion-SOA/emotion-server/pre/users.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="soa"
    xmlns="soa"
    elementFormDefault="qualified">
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="user">
          <xs:complexType>
            <xs:all>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="gender" type="xs:string"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="age" type="xs:int"/>
              <xs:element name="languages">
                <xs:complexType>
                  <xs:sequence maxOccurs="unbounded">
                    <xs:element name="language">
                      <xs:complexType>
                        <xs:all>
                          <xs:element name="name" type="xs:string"/>
                          <xs:element name="level" type="xs:string"/>
                        </xs:all>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Emotion-SOA/emotion-server/pre/users.xml
<?xml version="1.0"?>
<users
    xmlns="soa"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="soa users.xsd">
  <user>
    <name>Alice</name>
    <gender>Female</gender>
    <email>alice@example.com</email>
    <age>20</age>
    <languages>
      <language>
        <name>Java</name>
        <level>expert</level>
      </language>
      <language>
        <name>C</name>
        <level>familiar</level>
      </language>
      <language>
        <name>Python</name>
        <level>beginner</level>
      </language>
    </languages>
  </user>
  <user>
    <name>Bob</name>
    <gender>Male</gender>
    <email>bob@example.com</email>
    <age>21</age>
    <languages>
      <language>
        <name>JavaScript</name>
        <level>expert</level>
      </language>
      <language>
        <name>Java</name>
        <level>beginner</level>
      </language>
    </languages>
  </user>
</users>
